
public class TransactionFrame extends javax.swing.JFrame {
        
    private StoreData data;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransactionFrame.class.getName());

    /**
     * Creates new form TransactionFrame
     */
  public TransactionFrame(StoreData data) {
    this.data = data; // Connects the arrays
    initComponents(); // Don't delete this! It loads your design.

    // Puts your Rice, Sugar, etc. into the dropdown
    productbox.setModel(new javax.swing.DefaultComboBoxModel<>(data.products)); 
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        productbox = new javax.swing.JComboBox<>();
        qtyfield = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        buyButton = new javax.swing.JButton();
        inventoryButton = new javax.swing.JButton();
        logsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        productbox.setBackground(new java.awt.Color(255, 255, 204));
        productbox.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        productbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        productbox.addActionListener(this::productboxActionPerformed);

        qtyfield.setBackground(new java.awt.Color(255, 255, 204));
        qtyfield.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        qtyfield.addActionListener(this::qtyfieldActionPerformed);

        totalLabel.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        totalLabel.setText("WELCOME!");
        totalLabel.setMaximumSize(new java.awt.Dimension(58, 13));
        totalLabel.setRequestFocusEnabled(false);
        totalLabel.setVerifyInputWhenFocusTarget(false);

        buyButton.setBackground(new java.awt.Color(255, 255, 204));
        buyButton.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        buyButton.setText("BUY");
        buyButton.addActionListener(this::buyButtonActionPerformed);

        inventoryButton.setBackground(new java.awt.Color(255, 255, 204));
        inventoryButton.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        inventoryButton.setText("INVENTORY");
        inventoryButton.addActionListener(this::inventoryButtonActionPerformed);

        logsButton.setBackground(new java.awt.Color(255, 255, 204));
        logsButton.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        logsButton.setText("LOGS");

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabel1.setText("QUANTITY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qtyfield, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inventoryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyfield, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productbox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(logsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productboxActionPerformed

    private void qtyfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyfieldActionPerformed

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
try {
        // Get the selected product and the quantity typed in
        int index = productbox.getSelectedIndex();
        int qty = Integer.parseInt(qtyfield.getText());

        // Send it to the StoreData brain
        if (data.processTransaction(index, qty)) {
            // Success! Get the total cost and update the label
            double total = data.logTotals[data.transactionCount - 1];
            totalLabel.setText("Total: $" + total);
            javax.swing.JOptionPane.showMessageDialog(this, "Purchase Successful!");
        } else {
            // Failed: Not enough stock
            javax.swing.JOptionPane.showMessageDialog(this, "Not enough stock!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        // Failed: User typed text instead of a number
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid number for quantity.");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_buyButtonActionPerformed

    private void inventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButtonActionPerformed
    new InventoryFrame(data).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryButtonActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyButton;
    private javax.swing.JButton inventoryButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logsButton;
    private javax.swing.JComboBox<String> productbox;
    private javax.swing.JTextField qtyfield;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
